// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package test

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type One struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *One) Reset()         { *m = One{} }
func (m *One) String() string { return proto.CompactTextString(m) }
func (*One) ProtoMessage()    {}
func (*One) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_b2ff03819181e947, []int{0}
}
func (m *One) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_One.Unmarshal(m, b)
}
func (m *One) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_One.Marshal(b, m, deterministic)
}
func (dst *One) XXX_Merge(src proto.Message) {
	xxx_messageInfo_One.Merge(dst, src)
}
func (m *One) XXX_Size() int {
	return xxx_messageInfo_One.Size(m)
}
func (m *One) XXX_DiscardUnknown() {
	xxx_messageInfo_One.DiscardUnknown(m)
}

var xxx_messageInfo_One proto.InternalMessageInfo

func (m *One) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Two struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Two) Reset()         { *m = Two{} }
func (m *Two) String() string { return proto.CompactTextString(m) }
func (*Two) ProtoMessage()    {}
func (*Two) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_b2ff03819181e947, []int{1}
}
func (m *Two) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Two.Unmarshal(m, b)
}
func (m *Two) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Two.Marshal(b, m, deterministic)
}
func (dst *Two) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Two.Merge(dst, src)
}
func (m *Two) XXX_Size() int {
	return xxx_messageInfo_Two.Size(m)
}
func (m *Two) XXX_DiscardUnknown() {
	xxx_messageInfo_Two.DiscardUnknown(m)
}

var xxx_messageInfo_Two proto.InternalMessageInfo

func (m *Two) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*One)(nil), "One")
	proto.RegisterType((*Two)(nil), "Two")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_test_b2ff03819181e947) }

var fileDescriptor_test_b2ff03819181e947 = []byte{
	// 73 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x92, 0xe6, 0x62, 0xf6, 0xcf, 0x4b, 0x15, 0x12, 0xe1,
	0x62, 0x2d, 0x4b, 0xcc, 0x29, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70, 0x40,
	0x92, 0x21, 0xe5, 0xf9, 0xd8, 0x25, 0x93, 0xd8, 0xc0, 0x06, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x45, 0x9f, 0xde, 0xe6, 0x4e, 0x00, 0x00, 0x00,
}
